markdown: kramdown
highlighter: rouge
encoding: utf-8
exclude: ["node_modules", "files", "assets/css/main.scss", "assets/css/main.css", "gulpfile.js", "package.json", "package-lock.json", "README.md"]
permalink: pretty
# baseurl: https://www.jeansoto.com
baseurl: ''
